POST http://localhost:3000/v1/teacher/data HTTP/1.1
content-type: application/json

{
    "email":"teacher1@gmail.com",
    "stream":"it.teachers"
}
###
GET http://localhost:3000 HTTP/1.1
content-type: application/json

{
    
}
###

POST http://localhost:3000/v1/student/data HTTP/1.1
content-type: application/json

{
    "email":"student1@gmail.com",
    "stream":"stu.it.5.as"
}
###
POST http://localhost:3000/v1/message/send HTTP/1.1
content-type: application/json

{
    "emailto":"debjit",
    "emailfrom":"someone",
    "message":"hello"
}
###
POST http://localhost:3000/v1/message/receive HTTP/1.1
content-type: application/json

{
    "email":"debjit"
}
###
POST http://localhost:3000/v1 HTTP/1.1
content-type: application/json

{
    "email":"teacher1@gmail.com",
    "password":"teach123",
    "stream":"it.teachers"
}
###
POST  http://localhost:3000/v1/teacher/createstream HTTP/1.1
content-type: application/json

{
    "id":"Computer Science Engineering",
    "semester":[1,2,3,4,5,6,7,8],
    "section":[2,2,2,2,2,2,2,2]
}
###
GET http://localhost:3000/v1/student/attendance/it.5.as/1 HTTP/1.1
content-type: application/json

{
    
}